[tasks.check]
command = "cargo"
args = ["check"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.ci]
dependencies = ["fmt", "clippy", "test"]

[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]