//! Office metadata domain types.
//!
//! [`OfficeMetadata`] groups the core, extended, and custom properties stored
//! in an OOXML package. Use [`crate::ooxml::read_metadata`] to read an existing
//! package and [`crate::ooxml::write_metadata`] followed by package saving to
//! persist changes.

mod metadata_patch;

use serde::Serialize;
use std::collections::BTreeMap;

pub use metadata_patch::MetadataPatch;

/// Metadata stored in an OOXML package.
///
/// Core and extended properties correspond to the standard Office metadata
/// parts. Custom properties are application-defined string values.
///
/// [`crate::ooxml::write_metadata`] updates only the in-memory package; save
/// that package afterwards to publish the change.
///
/// # Examples
///
/// ```
/// use aigov::office::metadata::OfficeMetadata;
///
/// let mut metadata = OfficeMetadata::default();
/// metadata.core.title = Some("Quarterly report".into());
/// metadata.custom.insert("Department".into(), "Finance".into());
/// ```
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize)]
pub struct OfficeMetadata {
    /// Standard core properties.
    pub core: CoreMetadata,
    /// Standard Office extended properties and statistics.
    pub extended: ExtendedMetadata,
    /// Application-defined string properties keyed by name.
    pub custom: BTreeMap<String, String>,
}

/// Standard core properties for an Office document.
///
/// Date and version values are stored as strings. The library preserves the
/// supplied values and does not parse or validate them.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize)]
pub struct CoreMetadata {
    /// User-defined category.
    pub category: Option<String>,
    /// Workflow state, such as `Draft` or `Final`.
    pub content_status: Option<String>,
    /// User-defined content type.
    pub content_type: Option<String>,
    /// Creation timestamp, normally encoded as W3CDTF.
    pub created: Option<String>,
    /// Original document author.
    pub creator: Option<String>,
    /// Free-form description or abstract.
    pub description: Option<String>,
    /// User-defined identifier.
    pub identifier: Option<String>,
    /// Search keywords, stored as a comma-separated core property.
    pub keywords: Vec<String>,
    /// Language tag, such as `en-US`.
    pub language: Option<String>,
    /// Author of the most recent edit.
    pub last_modified_by: Option<String>,
    /// Timestamp of the most recent print operation.
    pub last_printed: Option<String>,
    /// Modification timestamp, normally encoded as W3CDTF.
    pub modified: Option<String>,
    /// Revision identifier.
    pub revision: Option<String>,
    /// Document subject.
    pub subject: Option<String>,
    /// Document title.
    pub title: Option<String>,
    /// User-defined version identifier.
    pub version: Option<String>,
}

/// Standard Office extended properties.
///
/// Values such as page and word counts are commonly generated by Office
/// applications. They are readable here but are not accepted by
/// [`MetadataPatch`].
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize)]
pub struct ExtendedMetadata {
    /// Version of the application that produced the document.
    pub app_version: Option<String>,
    /// Application that produced the document.
    pub application: Option<String>,
    /// Character count excluding spaces.
    pub characters: Option<u32>,
    /// Character count including spaces.
    pub characters_with_spaces: Option<u32>,
    /// Organization or company name.
    pub company: Option<String>,
    /// Digital-signature status or description supplied by the application.
    pub dig_sig: Option<String>,
    /// Application-defined document-security value.
    pub doc_security: Option<u32>,
    /// Heading names and their occurrence counts.
    pub heading_pairs: Vec<HeadingPair>,
    /// Whether hyperlinks changed since the last save.
    pub hyperlinks_changed: Option<bool>,
    /// Line count.
    pub lines: Option<u32>,
    /// Whether linked content is up to date.
    pub links_up_to_date: Option<bool>,
    /// Page count.
    pub pages: Option<u32>,
    /// Paragraph count.
    pub paragraphs: Option<u32>,
    /// Whether the document should scale cropping.
    pub scale_crop: Option<bool>,
    /// Whether the document is shared.
    pub shared_doc: Option<bool>,
    /// Template name or path.
    pub template: Option<String>,
    /// Titles of document parts, ordered by the producing application.
    pub titles_of_parts: Vec<String>,
    /// Total editing time in minutes.
    pub total_time: Option<u32>,
    /// Word count.
    pub words: Option<u32>,
}

/// A heading name and the number of times it occurs.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct HeadingPair {
    /// Heading name.
    pub name: String,
    /// Number of occurrences of the heading.
    pub count: u32,
}
